version: "3"

networks:
  jenkins_swarm:

volumes:
    jenkins-docker:
      driver: nimble
      driver_opts:
        sizeInGiB: 10

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
    restart: always
    networks:
      - jenkins_swarm
    volumes:
      - jenkins-docker:/var/jenkins_home

  worker:
    image: ffth/jenkins-swarm-slave:1.0
    command: -username jenkins -password jenkins -executors 1
    networks:
      - jenkins_swarm
    environment:
      - "JENKINS_PORT_8080_TCP_ADDR=jenkins"
      - "JENKINS_PORT_8080_TCP_PORT=8080"
